version: "3"
services:
  ipfs:
    image: "ipfs/go-ipfs"
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "5001:5001"
    command:
      [
        "daemon",
        "--migrate=true",
        "--agent-version-suffix=docker",
        "--enable-pubsub-experiment",
      ]
volumes:
  database-data:
  ipfs_staging:
  ipfs_data:
