version: "3"
services:
  ipfs:
    image: "ipfs/go-ipfs"
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "5001:5001"
    command:
      [
        "daemon",
        "--migrate=true",
        "--agent-version-suffix=docker",
        "--enable-pubsub-experiment",
      ]
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
volumes:
  database-data:
  ipfs_staging:
  ipfs_data:
  redis-data:
